import os
from detectron2.config import CfgNode as CN

def add_scenegraph_config(cfg):
    _C = cfg
    
    _C.GLOVE_DIR = '../glove/'
    _C.DEV_RUN = False
    ###################################################################################################

    _C.MODEL.SCENEGRAPH_ON = True
    _C.MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES = True
    _C.MODEL.USE_MASK_ON_NODE = False
    _C.MODEL.ROI_HEADS.OBJECTNESS_THRESH = 0.3
    _C.MODEL.GROUP_NORM = CN()
    _C.MODEL.GROUP_NORM.DIM_PER_GP = -1
    _C.MODEL.GROUP_NORM.NUM_GROUPS = 32
    _C.MODEL.GROUP_NORM.EPSILON = 1e-5 # default: 1e-5
    ###################################################################################################
    _C.MODEL.ROI_SCENEGRAPH_HEAD = CN()
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NAME = 'SceneGraphHead'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.MODE = 'predcls'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.REQUIRE_BOX_OVERLAP = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NUM_SAMPLE_PER_GT_REL = 4  # when sample fg relationship from gt, the max number of corresponding proposal pairs
    _C.MODEL.ROI_SCENEGRAPH_HEAD.BATCH_SIZE_PER_IMAGE = 64
    _C.MODEL.ROI_SCENEGRAPH_HEAD.POSITIVE_FRACTION = 0.25
    _C.MODEL.ROI_SCENEGRAPH_HEAD.DISABLE_MASKS_IN_SCENEGRAPH_HEAD = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_GT_BOX = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.MASK_REFINEMENT = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_GT_OBJECT_LABEL = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NMS_FILTER_DUPLICATES = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_FG_DOC_RELATION_WEIGHTS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_POOLING_DIM_COMPRESSED = 128
    _C.MODEL.ROI_SCENEGRAPH_HEAD.APPLY_ARGMAX_OVER_ALL_LOGITS_AND_FILTER_FG = False

    _C.MODEL.ROI_SCENEGRAPH_HEAD.RETURN_SEG_MASKS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.RETURN_SEG_ANNOS = False

    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_VISION = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_BIAS = True
    
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_MASK_ATTENTION = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.MASK_ATTENTION_TYPE = 'Weighted'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.SIGMOID_ATTENTION = True

    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICTOR = "MotifPredictor"
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NUM_CLASSES = 50
    _C.MODEL.ROI_SCENEGRAPH_HEAD.EMBED_DIM = 200
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_DROPOUT_RATE = 0.2
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_HIDDEN_DIM = 512
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_POOLING_DIM = 4096
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_OBJ_LAYER = 1  # assert >= 1
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_REL_LAYER = 1  # assert >= 1
    _C.MODEL.ROI_SCENEGRAPH_HEAD.ADD_GTBOX_TO_PROPOSAL_IN_TRAIN = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.ADD_GT_INSTANCES_TO_DETECTOR_TRAIN_PREDICTIONS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.SEG_BBOX_LOSS_MULTIPLIER = 1.0
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_ONLY_FG_PROPOSALS = True

    _C.MODEL.ROI_SCENEGRAPH_HEAD.LABEL_SMOOTHING_LOSS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.REL_PROP = [0.01858, 0.00057, 0.00051, 0.00109, 0.00150, 0.00489, 0.00432, 0.02913, 0.00245, 0.00121, 
                                       0.00404, 0.00110, 0.00132, 0.00172, 0.00005, 0.00242, 0.00050, 0.00048, 0.00208, 0.15608,
                                       0.02650, 0.06091, 0.00900, 0.00183, 0.00225, 0.00090, 0.00028, 0.00077, 0.04844, 0.08645,
                                       0.31621, 0.00088, 0.00301, 0.00042, 0.00186, 0.00100, 0.00027, 0.01012, 0.00010, 0.01286,
                                       0.00647, 0.00084, 0.01077, 0.00132, 0.00069, 0.00376, 0.00214, 0.11424, 0.01205, 0.02958]

    _C.MODEL.ROI_SCENEGRAPH_HEAD.ZERO_SHOT_TRIPLETS = '../evaluation/datasets/vg/zeroshot_triplet.pytorch'

    #TransformerContext
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER = CN()
    # for TransformerPredictor only
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.DROPOUT_RATE = 0.1   
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.OBJ_LAYER = 4        
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.REL_LAYER = 2        
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.NUM_HEAD = 8         
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.INNER_DIM = 2048     
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.KEY_DIM = 64         
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.VAL_DIM = 64     
    ###################################################################################################
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS = CN()
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.NAME = 'BoxFeatureExtractor'
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_RESOLUTION = 28
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_TYPE = 'ROIAlignV2'
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.BOX_FEATURE_MASK = True 
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.CLASS_LOGITS_WITH_MASK = False

    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS = CN()
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.NAME = 'RelationFeatureExtractor'
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.USE_MASK_COMBINER = False
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.MULTIPLY_LOGITS_WITH_MASKS = False

    # Overlap threshold for an RoI to be considered foreground (if >= FG_IOU_THRESHOLD)
    _C.MODEL.ROI_HEADS.FG_IOU_THRESHOLD = 0.5
    _C.MODEL.ROI_HEADS.REFINE_SEG_MASKS = False
    _C.MODEL.ROI_HEADS.SEGMENTATION_STEP_MASK_REFINE = True

    # Settings for relation testing
    _C.TEST.RELATION = CN()
    _C.TEST.RELATION.REQUIRE_OVERLAP = True
    _C.TEST.RELATION.LATER_NMS_PREDICTION_THRES = 0.3
    _C.TEST.RELATION.LATER_OBJECT_SCORE_THRES = None #disabled, if set to None. otherwise, uses late thresholding and nms similar to original frcnn head
    _C.TEST.RELATION.MULTIPLE_PREDS = False
    _C.TEST.RELATION.IOU_THRESHOLD = 0.5

    _C.TEST.RELATION.USE_ADVANCED_GRAMMAR_POSTPROCESSING = False

    _C.DATASETS.VISUAL_GENOME.CLIPPED = False

    _C.TEST.USE_DOCUMENT_HEURISTICS = False
    _C.TEST.USE_DOCUMENT_HEURISTICS_DATASET_TYPE = "ADtgt"
    _C.TEST.DOCUMENT_HEURISTICS_ACTIVATE_POSTPROCESSING_LOOP = False
    
    _C.TEST.USE_GRAMMAR_POSTPROCESSING = False